documentation:
  - changed-files:
    - any-glob-to-any-file: ['docs/*', 'docs/**/*', 'mkdocs.yml']

github-actions:
  - changed-files:
      - any-glob-to-any-file: ['.github/workflows/*',
       '.github/workflows/**/*',
       '.github/dependabot.yml',
       '.github/boring-cyborg.yml',
       '..github/release-drafter.yml',
       '.github/semantic.yml',
       '.github/stale.yml',
       '.github/mergify.yml',
       '.github/labeler.yml']

github-templates:
  - changed-files:
      - any-glob-to-any-file: ['.github/ISSUE_TEMPLATE/*',
       '.github/PULL_REQUEST_TEMPLATE.md',
       '.github/.chglog/*',
       '.github/.chglog/**/*']

internal:
  - changed-files:
      - any-glob-to-any-file: ['.flake8',
       '.bandit.baseline',
       '.gitignore',
       '.pre-commit-config.yaml',
       'MANIFEST.in',
       'Makefile',
       'CONTRIBUTING.md',
       'MAINTAINERS.md',
       'CODE_OF_CONDUCT.md',
       'LICENSE',
       'THIRD-PARTY-LICENSES',
       '.dockerignore',
       '.editorconfig',
       'setup.cfg']

dependencies:
  - changed-files:
      - any-glob-to-any-file: ['pyproject.toml',
      'poetry.lock',
      'requirements.txt']

tests:
  - changed-files:
      - any-glob-to-any-file: ['automated_tests/*',
       'automated_tests/**/*',
       'tests/*',
       'tests/**/*']

build:
  - changed-files:
        - any-glob-to-any-file: ['Dockerfile',
        'Dockerfile.*',
        'docker-compose.yml',
        'docker-compose.*.yml',
        'docker-compose.*.yaml',
        'docker-compose.*.yaml',
        'docker-compose']

golang:
  - changed-files:
      - any-glob-to-any-file: ['go.mod',
      'go.sum',
      '**/*.go']

javascript:
  - changed-files:
      - any-glob-to-any-file: '**/*.json'

json:
  - changed-files:
      - any-glob-to-any-file: '**/*.json'

markdown:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

python:
  - changed-files:
      - any-glob-to-any-file: ['requirements.txt', '**/*.py']

sql:
  - changed-files:
      - any-glob-to-any-file: '**/*.sql'

typescript:
  - changed-files:
      - any-glob-to-any-file: ['**/*.ts', '**/*.tsx']
