documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - docs/*
              - docs/**/*
              - mkdocs.yml

github-actions:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - .github/workflows/*
              - .github/workflows/**/*
              - .github/dependabot.yml
              - .github/boring-cyborg.yml
              - .github/release-drafter.yml
              - .github/semantic.yml
              - .github/stale.yml
              - .github/mergify.yml
              - .github/labeler.yml

github-templates:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - .github/ISSUE_TEMPLATE/*
              - .github/PULL_REQUEST_TEMPLATE.md
              - .github/.chglog/*
              - .github/.chglog/**/*

internal:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - .flake8
              - .bandit.baseline
              - .gitignore
              - .pre-commit-config.yaml
              - MANIFEST.in
              - Makefile
              - CONTRIBUTING.md
              - MAINTAINERS.md
              - CODE_OF_CONDUCT.md
              - LICENSE
              - THIRD-PARTY-LICENSES
              - .dockerignore
              - .editorconfig
              - setup.cfg

dependencies:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - pyproject.toml
              - poetry.lock
              - requirements.txt

tests:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - tests/*
              - tests/**/*
              - automated_tests/*
              - automated_tests/**/*

build:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - Dockerfile

golang:
  - any:
      - changed-files:
          - "**/*.go"

javascript:
  - any:
      - changed-files:
          - "**/*.json"

json:
  - any:
      - changed-files:
          - "**/*.json"

markdown:
  - any:
      - changed-files:
          - "**/*.md"

python:
  - any:
      - changed-files:
          - "**/*.py"

sql:
  - any:
      - changed-files:
          - "**/*.py"

typescript:
  - any:
      - changed-files:
          - "**/*.ts"
          - "**/*.tsx"
