# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fleet
spec:
  selector:
    app: {{ .Release.Name }}
    component: fleet
  ports:
    - protocol: TCP
      port: {{ .Values.fleet.httpPort }}
      name: {{ .Release.Name }}-fleet-http
