# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sinks
spec:
  selector:
    app: {{ .Release.Name }}
    component: sinks
  ports:
    - protocol: TCP
      port: {{ .Values.sinks.httpPort }}
      name: {{ .Release.Name }}-sinks-http
