version: "1.0"

pktvisor:
  taps:
    anycast:
      type: pcap
      config:
        iface: eth0
sinks:

orb:
  vitals:
    region: EU
    pop: ams02
    node_type: dns
  datasource:
    # TODO: allow different types
    # type: consul
    address: http://127.0.0.1:8500
    access_token: "" #optional
    tls: # optional
      cert: # path
      key: # path
      rootCA: # path
      verify: # bool