version: "1.0"

visor:
  taps:
    mydefault:
      input_type: pcap
      config:
        iface: "eth0"

orb:
  backends:
    pktvisor:
      binary: "/usr/local/sbin/pktvisord"
      config_file: "/etc/orb/agent.yaml"
  tags:
    region: EU
    pop: ams02
    node_type: dns
  cloud:
    config:
      #agent_name: auto-provisioned
      auto_provision: true
    api:
      address: https://api.orb.live
      token: TOKEN
    mqtt:
      address: tls://127.0.0.1:8883
  #      id: "f420a133-7651-412d-852a-6141fafeaea5"
  #      key: "14ae65ae-092f-4fdc-be6a-0cfb378119dc"
  #      channel_id: "9610b0a4-b05f-46e5-a32d-000d8a2ec1fd"
  # optional TLS config
  tls:
    verify: true
