listener:
  bind_addr: "0.0.0.0:8080"
  tls: 
    auto:
      enabled: false
      domain: ""
      cache_dir: /var/run/orb/.cache_dir
    cert: ""
    key: ""
loggers:
  access_log:
    path: /dev/stdout
  error_log:
    level: debug
    path: /dev/stderr
services:
  datasource:
    # TODO: allow different types
    #type: consul
    address: http://127.0.0.1:8500
    access_token: "" #optional
    tls: # optional
      cert: # path
      key: # path
      rootCA: # path
      verify: # bool