version: "3.7"

networks:
  otelcol:
    driver: bridge

services:
  # Sample Go application producing counter metrics.
  agent:
    container_name: agent
    build:
      context: ""
    networks:
      - otelcol
    restart: always
  # The Prometheus server:
  # OpenTelemetry Collector
  otelcollector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    container_name: otelcollector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    networks:
      - otelcol
    depends_on:
      - agent
