receivers:
  prometheus_simple:
    collection_interval: 10s
    # the federation endpoint:
    # Read more about it here: https://prometheus.io/docs/prometheus/latest/federation/
    # You can query the federation with PromQL, encoded as part of the query string.
    endpoint: orb-agent:10853
    metrics_path: /api/v1/policies/__all/metrics/prometheus
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  telemetry:
    logs:
      level: "DEBUG"
  extensions: [pprof, zpages, health_check]
  pipelines:
    metrics:
      receivers: [prometheus_simple]
      processors: [batch]
      exporters: [logging]
