name: test-slack-post

on:
  pull_request:
    branches: [ slack-post ]
  push:
    branches: [ slack-post ]

jobs:
  post-slack-channel:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v2

      - name: Set branch name
        shell: bash
        run: |
          echo "BRANCH_NAME=production" >> $GITHUB_ENV

      - name: Generate ref tag (production)
        run: |
          echo "REF_TAG=production" >> $GITHUB_ENV

      - name: Get VERSION
        run: |
          echo "VERSION=`cat ${{github.workspace}}/VERSION`" >> $GITHUB_ENV

      - name: Debug VERSION
        run: echo ${{ env.VERSION }}

      - name: Get short commit hash to a variable
        id: commit_hash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Post on slack
        uses: ./.github/actions/slack-post
        with:
          branch: develop
          dir: orb
          slack_channel: C02SEF78ZPT
          slack_token: ${{secrets.SLACK_APP_TOKEN}}